networks:
  backend:
  frontend:

services:
  ieltsbe:
    build:
      context: .
      dockerfile: ielts-web-api/ielts.api/Dockerfile
    ports:
      - ${BE_PORT}:8080
    networks:
      - backend
    image: zurachan/ielts-be:1.0.0
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_SA_PASSWORD=${DB_SA_PASSWORD}
      - IP_SERVER=${IP_SERVER}
      - FE_PORT=${FE_PORT}
     
  ieltsapp:
    build:
      context: ./ielts-web-app
      dockerfile: ./Dockerfile
    ports:
      - ${FE_PORT}:80
    networks:
      - frontend
    image: zurachan/ielts-fe:1.0.0
    depends_on:
      - ieltsbe
     